<?xml version="1.0" encoding="ISO-8859-1"?>
<project
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0">
    <!-- @version $Revision: 1998 $ ($Author: vlads $) $Date: 2009-04-07 09:00:20 -0500 (Tue, 07 Apr 2009) $ -->
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.microemu</groupId>
        <artifactId>microemu</artifactId>
        <version>3.0.0-SNAPSHOT</version><!--me-version-->
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>microemu-javase</artifactId>
    <name>microemu-javase</name>

    <description>javase</description>

    <dependencies>
        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midp</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>J2MEOnlyJavaLibrary</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>CommonJavaLibrary</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <!-- moved to microemu-javase-swing and swt -->
        <!--
        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-injected</artifactId>
            <version>${project.version}</version>
            <classifier>inject</classifier>
        </dependency>
        -->

<!-- newer versions org.ow2.asm -->
<!--  
        <dependency>
            <groupId>asm</groupId>
            <artifactId>asm-all</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>asm</groupId>
            <artifactId>asm-all</artifactId>
            <version>3.3.1</version>
            <classifier>sources</classifier>
        </dependency>
-->

<!--
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
-->
    </dependencies>

    <build>
        <!-- TWB - we don't want to run the tests -->
        <testSourceDirectory>sr2</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <!-- 
                <version>2.5.1</version>
                <version>2.3.2</version>
                -->
                <configuration> 
                    <source>1.8</source>
                    <target>1.8</target>
                    <compilerArgument>-Xlint:all</compilerArgument>
                    <showWarnings>true</showWarnings>
                    <showDeprecation>true</showDeprecation>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
        </plugins>
    </build>
</project>