/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.util.BasicArrayList;


/**
 * This is currently added only for infinite maps. The contents of a<br>
 * chunk element is same as that of the data element, except it<br>
 * stores the 'data' of the area specified in the attributes.
 * 
 */
public class Chunk {

    /**
     * 
     */
        
    protected BasicArrayList tile;
    /**
     * The x coordinate of the chunk in tiles.
     * 
     */
        
    protected Integer x;
    /**
     * The y coordinate of the chunk in tiles.
     * 
     */
        
    protected Integer y;
    /**
     * The width of the chunk in tiles.
     * 
     */
        
    protected Integer width;
    /**
     * The height of the chunk in tiles.
     * 
     */
        
    protected Integer height;

    /**
     * 
     */
    
    public BasicArrayList getTile() {
        if (tile == null) {
            tile = new BasicArrayList();
        }
        return this.tile;
    }

    /**
     * The x coordinate of the chunk in tiles.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getX() {
        return x;
    }

    /**
     * The x coordinate of the chunk in tiles.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setX(Integer value) {
        this.x = value;
    }

    /**
     * The y coordinate of the chunk in tiles.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getY() {
        return y;
    }

    /**
     * The y coordinate of the chunk in tiles.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setY(Integer value) {
        this.y = value;
    }

    /**
     * The width of the chunk in tiles.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getWidth() {
        return width;
    }

    /**
     * The width of the chunk in tiles.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setWidth(Integer value) {
        this.width = value;
    }

    /**
     * The height of the chunk in tiles.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getHeight() {
        return height;
    }

    /**
     * The height of the chunk in tiles.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setHeight(Integer value) {
        this.height = value;
    }

}
