/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;



/**
 * This element is only used in case of isometric orientation, and<br>
 * determines how tile overlays for terrain and collision<br>
 * information are rendered.
 * 
 */


public class Grid {

    /**
     * Orientation of the grid for the tiles in this tileset<br>
     * (orthogonal or isometric)
     * 
     */
        
    protected Orientation orientation;
    /**
     * Width of a grid cell
     * 
     */
        
    protected Integer width;
    /**
     * Height of a grid cell
     * 
     */
        
    protected Integer height;

    /**
     * Orientation of the grid for the tiles in this tileset<br>
     * (orthogonal or isometric)
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    
    public Orientation getOrientation() {
        return this.orientation;
    }

    /**
     * Orientation of the grid for the tiles in this tileset<br>
     * (orthogonal or isometric)
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    
    public void setOrientation(Orientation value) {
        this.orientation = value;
    }

    /**
     * Width of a grid cell
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getWidth() {
        return this.width;
    }

    /**
     * Width of a grid cell
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setWidth(Integer value) {
        this.width = value;
    }

    /**
     * Height of a grid cell
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getHeight() {
        return this.height;
    }

    /**
     * Height of a grid cell
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setHeight(Integer value) {
        this.height = value;
    }

}
