/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.string.StringUtil;



/**
 * Note that it is not currently possible to use Tiled to create<br>
 * maps with embedded image data, even though the TMX format<br>
 * supports this. It is possible to create such maps using<br>
 * `libtiled` (Qt/C++) or<br>
 * [tmxlib](https://pypi.python.org/pypi/tmxlib) (Python).
 * 
 */
public class ImageData {

    /**
     * @since 0.9
     * 
     */
     
    protected Data dataP = Data.NULL_DATA;
    /**
     * Used for embedded images, in combination with a `data` child<br>
     * element. Valid values are file extensions like `png`, `gif`,<br>
     * `jpg`, `bmp`, etc.<br>
     * <br>
     * @since 0.9
     * 
     */
        
    protected String formatP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * Used by some versions of Tiled Java.<br>
     * <br>
     * @deprecated and unsupported by Tiled Qt.
     * 
     */
    //@Deprecated
    protected int idP;
    /**
     * The reference to the tileset image file<br>
     * (Tiled supports most common image formats).<br>
     * <br>
     * @since 0.9
     * 
     */
            
    protected String sourceP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * Defines a specific color that is treated as transparent<br>
     * (example value: "#FF00FF" for magenta). Up until Tiled 0.12,<br>
     * this value is written out without a `#` but this is planned<br>
     * to change.
     * 
     */
        
    protected String transP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The image width in pixels (optional, used for tile index<br>
     * correction when the image changes)
     * 
     */
        
    protected int widthP;
    /**
     * The image height in pixels (optional)
     * 
     */
        
    protected int heightP;

    public String path = StringUtil.getInstance().EMPTY_STRING;
    
    /**
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    
    public Data getData() {
        return this.dataP;
    }

    /**
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    
    public void setData(Data value) {
        this.dataP = value;
    }

    /**
     * Used for embedded images, in combination with a `data` child<br>
     * element. Valid values are file extensions like `png`, `gif`,<br>
     * `jpg`, `bmp`, etc.<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getFormat() {
        return this.formatP;
    }

    /**
     * Used for embedded images, in combination with a `data` child<br>
     * element. Valid values are file extensions like `png`, `gif`,<br>
     * `jpg`, `bmp`, etc.<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setFormat(String value) {
        this.formatP = value;
    }

    /**
     * Used by some versions of Tiled Java.<br>
     * <br>
     * @deprecated and unsupported by Tiled Qt.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    //@Deprecated
    
    public int getId() {
        return this.idP;
    }

    /**
     * Used by some versions of Tiled Java.<br>
     * <br>
     * @deprecated and unsupported by Tiled Qt.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    //@Deprecated
    
    public void setId(int value) {
        this.idP = value;
    }

    /**
     * The reference to the tileset image file<br>
     * (Tiled supports most common image formats).<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getSource() {
        return this.sourceP;
    }

    /**
     * The reference to the tileset image file<br>
     * (Tiled supports most common image formats).<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setSource(String value) {
        this.sourceP = value;
    }

    /**
     * Defines a specific color that is treated as transparent<br>
     * (example value: "#FF00FF" for magenta). Up until Tiled 0.12,<br>
     * this value is written out without a `#` but this is planned<br>
     * to change.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getTrans() {
        return this.transP;
    }

    /**
     * Defines a specific color that is treated as transparent<br>
     * (example value: "#FF00FF" for magenta). Up until Tiled 0.12,<br>
     * this value is written out without a `#` but this is planned<br>
     * to change.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setTrans(String value) {
        this.transP = value;
    }

    /**
     * The image width in pixels (optional, used for tile index<br>
     * correction when the image changes)
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getWidth() {
        return this.widthP;
    }

    /**
     * The image width in pixels (optional, used for tile index<br>
     * correction when the image changes)
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setWidth(int value) {
        this.widthP = value;
    }

    /**
     * The image height in pixels (optional)
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getHeight() {
        return this.heightP;
    }

    /**
     * The image height in pixels (optional)
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setHeight(int value) {
        this.heightP = value;
    }

}
