/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.java.bool.BooleanFactory;
import org.allbinary.logic.string.StringUtil;

/**
 * 
 */
public abstract class LayerData {

    protected Properties propertiesP = new Properties();
    /**
     * Unique ID of the layer. Each layer that is added to a map gets a<br>
     * unique id. Even if a layer is deleted, no layer ever gets the<br>
     * same ID. Can not be changed in Tiled. <br>
     * <br>
     * @since 1.2
     * 
     */
    protected int idP;
    /**
     * The name of the layer.
     * 
     */
        
    protected String nameP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The x coordinate of the layer in tiles. Defaults to 0 and<br>
     * can no longer be changed in Tiled Qt.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated
    protected int xP;
    /**
     * The y coordinate of the layer in tiles. Defaults to 0 and<br>
     * can no longer be changed in Tiled Qt.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated    
    protected int yP;
    /**
     * The width of the layer in tiles. Traditionally required, but<br>
     * as of Tiled Qt always the same as the map width.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated
    protected int widthP;
    /**
     * The height of the layer in tiles. Traditionally required,<br>
     * but as of Tiled Qt always the same as the map height.<br>
     * <br>
     * @deprecated
     * 
     */
        //@Deprecated
    
    protected int heightP;
    /**
     * The opacity of the layer as a value from 0 to 1. Defaults to<br>
     *  1.
     * 
     */
        
    protected Float opacityP = Float.valueOf(0.0f);
    /**
     * Whether the layer is shown (1) or hidden (0). Defaults to 1.
     * 
     */
        
    protected Boolean visibleP = BooleanFactory.getInstance().FALSE;
    /**
     * Rendering offset for this layer in pixels. Defaults to 0.<br>
     * <br>
     * @since 0.14
     * 
     */
        
    protected int offsetXP;
    /**
     * Rendering offset for this layer in pixels. Defaults to 0.<br>
     * <br>
     * @since 0.14
     * 
     */
        
    protected int offsetYP;
    /**
     * Locking flag of the layer (used by Tiled).
     * 
     */
        
    protected int lockedP;

    /**
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    
    public Properties getProperties() {
        return this.propertiesP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    
    public void setProperties(Properties value) {
        this.propertiesP = value;
    }

    /**
     * Unique ID of the layer. Each layer that is added to a map gets a<br>
     * unique id. Even if a layer is deleted, no layer ever gets the<br>
     * same ID. Can not be changed in Tiled. <br>
     * <br>
     * @since 1.2
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getId() {
        return this.idP;
    }

    /**
     * Unique ID of the layer. Each layer that is added to a map gets a<br>
     * unique id. Even if a layer is deleted, no layer ever gets the<br>
     * same ID. Can not be changed in Tiled. <br>
     * <br>
     * @since 1.2
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setId(int value) {
        this.idP = value;
    }

    /**
     * The name of the layer.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return this.nameP;
    }

    /**
     * The name of the layer.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.nameP = value;
    }

    /**
     * The x coordinate of the layer in tiles. Defaults to 0 and<br>
     * can no longer be changed in Tiled Qt.<br>
     * <br>
     * @deprecated
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    //@Deprecated
    
    public int getX() {
        return this.xP;
    }

    /**
     * The x coordinate of the layer in tiles. Defaults to 0 and<br>
     * can no longer be changed in Tiled Qt.<br>
     * <br>
     * @deprecated
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    //@Deprecated
    
    public void setX(int value) {
        this.xP = value;
    }

    /**
     * The y coordinate of the layer in tiles. Defaults to 0 and<br>
     * can no longer be changed in Tiled Qt.<br>
     * <br>
     * @deprecated
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    //@Deprecated
    
    public int getY() {
        return this.yP;
    }

    /**
     * The y coordinate of the layer in tiles. Defaults to 0 and<br>
     * can no longer be changed in Tiled Qt.<br>
     * <br>
     * @deprecated
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    //@Deprecated
    
    public void setY(int value) {
        this.yP = value;
    }

    /**
     * The width of the layer in tiles. Traditionally required, but<br>
     * as of Tiled Qt always the same as the map width.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated
    
    public int getWidth() {
        return this.widthP;
    }

    /**
     * The width of the layer in tiles. Traditionally required, but<br>
     * as of Tiled Qt always the same as the map width.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated
    
    public void setWidth(int value) {
        this.widthP = value;
    }

    /**
     * The height of the layer in tiles. Traditionally required,<br>
     * but as of Tiled Qt always the same as the map height.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated
    
    public int getHeight() {
        return this.heightP;
    }

    /**
     * The height of the layer in tiles. Traditionally required,<br>
     * but as of Tiled Qt always the same as the map height.<br>
     * <br>
     * @deprecated
     * 
     */
    //@Deprecated
    
    public void setHeight(int value) {
        this.heightP = value;
    }

    /**
     * The opacity of the layer as a value from 0 to 1. Defaults to<br>
     *  1.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    
    public Float getOpacity() {
        return this.opacityP;
    }

    /**
     * The opacity of the layer as a value from 0 to 1. Defaults to<br>
     *  1.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    
    public void setOpacity(Float value) {
        this.opacityP = value;
    }

    /**
     * Whether the layer is shown (1) or hidden (0). Defaults to 1.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isVisible() {
        return this.visibleP;
    }

    /**
     * Whether the layer is shown (1) or hidden (0). Defaults to 1.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setVisible(Boolean value) {
        this.visibleP = value;
    }

    /**
     * Rendering offset for this layer in pixels. Defaults to 0.<br>
     * <br>
     * @since 0.14
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getOffsetX() {
        return this.offsetXP;
    }

    /**
     * Rendering offset for this layer in pixels. Defaults to 0.<br>
     * <br>
     * @since 0.14
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setOffsetX(int value) {
        this.offsetXP = value;
    }

    /**
     * Rendering offset for this layer in pixels. Defaults to 0.<br>
     * <br>
     * @since 0.14
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getOffsetY() {
        return this.offsetYP;
    }

    /**
     * Rendering offset for this layer in pixels. Defaults to 0.<br>
     * <br>
     * @since 0.14
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setOffsetY(int value) {
        this.offsetYP = value;
    }

    /**
     * Locking flag of the layer (used by Tiled).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getLocked() {
        return this.lockedP;
    }

    /**
     * Locking flag of the layer (used by Tiled).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setLocked(int value) {
        this.lockedP = value;
    }

}
