/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.string.StringUtil;
import org.allbinary.util.BasicArrayList;
import org.allbinary.util.BasicArrayListD;

/**
 * The `tilewidth` and `tileheight` properties determine the<br>
 * general grid size of the map. The individual tiles may have<br>
 * different sizes. Larger tiles will extend at the top and right<br>
 * (anchored to the bottom left).<br>
 * <br>
 * A map contains three different kinds of layers. Tile layers were<br>
 * once the only type, and are simply called layer, object layers<br>
 * have the objectgroup tag and image layers use the imagelayer<br>
 * tag. The order in which these layers appear is the order in<br>
 * which the layers are rendered by Tiled.
 * 
 */
public class MapData {

    /**
     * 
     */
    protected Properties propertiesP = new Properties();
    /**
     * 
     */
    protected BasicArrayList tileSetsP = new BasicArrayListD();
    /**
     * 
     */
    protected BasicArrayList layersP = new BasicArrayListD();
    /**
     * The TMX format version. Was "1.0" so far, and will be<br>
     * incremented to match minor Tiled releases.
     * 
     */
    protected String versionP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The Tiled version used to save the file.<br>
     * May be a date (for snapshot builds).<br>
     * <br>
     * @since 1.0.1
     * 
     */
    protected String tiledversionP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * Map orientation. Tiled supports "orthogonal", "isometric",<br>
     * "staggered" (since 0.9) and "hexagonal" (since 0.11).
     * 
     */
    protected Orientation orientationP = Orientation.HEXAGONAL;
    /**
     * The order in which tiles on tile layers are rendered. Valid<br>
     * values are `right-down` (the default), `right-up`,<br>
     * `left-down` and `left-up`. In all cases, the map is drawn<br>
     * row-by-row. (since 0.10, but only supported for orthogonal<br>
     * maps at the moment)
     * 
     */
    protected RenderOrder renderorderP = RenderOrder.LEFT_UP;
    /**
     * The map width in tiles.
     * 
     */
    protected int widthP;
    /**
     * The map height in tiles.
     * 
     */
    protected int heightP;
    /**
     * The width of a tile.
     * 
     */
    protected int tileWidthP;
    /**
     * The height of a tile.
     * 
     */
    protected int tileHeightP;
    /**
     * Infinite maps give you independence from bounds of the map.<br>
     * <br>
     * @since 1.1
     * 
     */
    protected int infiniteP;
    /**
     * Only for hexagonal maps. Determines the width or height<br>
     * (depending on the staggered axis) of the tile's edge, in<br>
     * pixels.
     * 
     */
    protected int hexSideLengthP;
    /**
     * For staggered and hexagonal maps, determines which axis<br>
     * ("x" or "y") is staggered.<br>
     * <br>
     * @since 0.11
     * 
     */
    protected StaggerAxis staggerAxisP = StaggerAxis.X;
    /**
     * For staggered and hexagonal maps, determines whether the<br>
     * "even" or "odd" indexes along the staggered axis are<br>
     * shifted.<br>
     * <br>
     * @since 0.11
     * 
     */
    protected StaggerIndex staggerIndexP = StaggerIndex.EVEN;
    /**
     * The background color of the map. (optional, may include<br>
     * alpha value since 0.15 in the form `#AARRGGBB`)<br>
     * <br>
     * @since 0.9
     * 
     */
    protected String backgroundcolorP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * Stores the next available ID for new layers. This number is<br>
     * stored to prevent reuse of the same ID after layers have been<br>
     * removed.<br>
     * <br>
     * @since 1.2
     * 
     */
    protected int nextlayeridP;
    /**
     * Stores the next available ID for new objects. This number<br>
     * is stored to prevent reuse of the same ID after objects<br>
     * have been removed.<br>
     * <br>
     * @since 0.11
     * 
     */
    protected int nextobjectidP;

    /**
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    public Properties getProperties() {
        return this.propertiesP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    public void setProperties(Properties value) {
        this.propertiesP = value;
    }

    /**
     * 
     */
    public BasicArrayList getTileSets() {
        return this.tileSetsP;
    }

    /**
     * 
     */
    public BasicArrayList getLayers() {
        return this.layersP;
    }

    /**
     * The TMX format version. Was "1.0" so far, and will be<br>
     * incremented to match minor Tiled releases.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (this.versionP == null) {
            return "1.0";
        } else {
            return this.versionP;
        }
    }

    /**
     * The TMX format version. Was "1.0" so far, and will be<br>
     * incremented to match minor Tiled releases.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.versionP = value;
    }

    /**
     * The Tiled version used to save the file.<br>
     * May be a date (for snapshot builds).<br>
     * <br>
     * @since 1.0.1
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getTiledversion() {
        return this.tiledversionP;
    }

    /**
     * The Tiled version used to save the file.<br>
     * May be a date (for snapshot builds).<br>
     * <br>
     * @since 1.0.1
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setTiledversion(String value) {
        this.tiledversionP = value;
    }

    /**
     * Map orientation. Tiled supports "orthogonal", "isometric",<br>
     * "staggered" (since 0.9) and "hexagonal" (since 0.11).
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    
    public Orientation getOrientation() {
        return this.orientationP;
    }

    /**
     * Map orientation. Tiled supports "orthogonal", "isometric",<br>
     * "staggered" (since 0.9) and "hexagonal" (since 0.11).
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    
    public void setOrientation(Orientation value) {
        this.orientationP = value;
    }

    /**
     * The order in which tiles on tile layers are rendered. Valid<br>
     * values are `right-down` (the default), `right-up`,<br>
     * `left-down` and `left-up`. In all cases, the map is drawn<br>
     * row-by-row. (since 0.10, but only supported for orthogonal<br>
     * maps at the moment)
     * 
     * @return
     *     possible object is
     *     {@link RenderOrder }
     *     
     */
    
    public RenderOrder getRenderorder() {
        if (this.renderorderP == null) {
            return RenderOrder.RIGHT_DOWN;
        } else {
            return this.renderorderP;
        }
    }

    /**
     * The order in which tiles on tile layers are rendered. Valid<br>
     * values are `right-down` (the default), `right-up`,<br>
     * `left-down` and `left-up`. In all cases, the map is drawn<br>
     * row-by-row. (since 0.10, but only supported for orthogonal<br>
     * maps at the moment)
     * 
     * @param value
     *     allowed object is
     *     {@link RenderOrder }
     *     
     */
    
    public void setRenderorder(RenderOrder value) {
        this.renderorderP = value;
    }

    /**
     * The map width in tiles.
     * 
     */
    
    public int getWidth() {
        return this.widthP;
    }

    /**
     * The map width in tiles.
     * 
     */
    
    public void setWidth(int value) {
        this.widthP = value;
    }

    /**
     * The map height in tiles.
     * 
     */
    
    public int getHeight() {
        return this.heightP;
    }

    /**
     * The map height in tiles.
     * 
     */
    
    public void setHeight(int value) {
        this.heightP = value;
    }

    /**
     * The width of a tile.
     * 
     */
    
    public int getTileWidth() {
        return this.tileWidthP;
    }

    /**
     * The width of a tile.
     * 
     */
    
    public void setTileWidth(int value) {
        this.tileWidthP = value;
    }

    /**
     * The height of a tile.
     * 
     */
    
    public int getTileHeight() {
        return this.tileHeightP;
    }

    /**
     * The height of a tile.
     * 
     */
    
    public void setTileHeight(int value) {
        this.tileHeightP = value;
    }

    /**
     * Infinite maps give you independence from bounds of the map.<br>
     * <br>
     * @since 1.1
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getInfinite() {
        return this.infiniteP;
    }

    /**
     * Infinite maps give you independence from bounds of the map.<br>
     * <br>
     * @since 1.1
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setInfinite(int value) {
        this.infiniteP = value;
    }

    /**
     * Only for hexagonal maps. Determines the width or height<br>
     * (depending on the staggered axis) of the tile's edge, in<br>
     * pixels.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getHexSideLength() {
        return this.hexSideLengthP;
    }

    /**
     * Only for hexagonal maps. Determines the width or height<br>
     * (depending on the staggered axis) of the tile's edge, in<br>
     * pixels.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setHexSideLength(int value) {
        this.hexSideLengthP = value;
    }

    /**
     * For staggered and hexagonal maps, determines which axis<br>
     * ("x" or "y") is staggered.<br>
     * <br>
     * @since 0.11
     * 
     * @return
     *     possible object is
     *     {@link StaggerAxis }
     *     
     */
    
    public StaggerAxis getStaggerAxis() {
        return this.staggerAxisP;
    }

    /**
     * For staggered and hexagonal maps, determines which axis<br>
     * ("x" or "y") is staggered.<br>
     * <br>
     * @since 0.11
     * 
     * @param value
     *     allowed object is
     *     {@link StaggerAxis }
     *     
     */
    
    public void setStaggerAxis(StaggerAxis value) {
        this.staggerAxisP = value;
    }

    /**
     * For staggered and hexagonal maps, determines whether the<br>
     * "even" or "odd" indexes along the staggered axis are<br>
     * shifted.<br>
     * <br>
     * @since 0.11
     * 
     * @return
     *     possible object is
     *     {@link StaggerIndex }
     *     
     */
    
    public StaggerIndex getStaggerIndex() {
        return this.staggerIndexP;
    }

    /**
     * For staggered and hexagonal maps, determines whether the<br>
     * "even" or "odd" indexes along the staggered axis are<br>
     * shifted.<br>
     * <br>
     * @since 0.11
     * 
     * @param value
     *     allowed object is
     *     {@link StaggerIndex }
     *     
     */
    
    public void setStaggerIndex(StaggerIndex value) {
        this.staggerIndexP = value;
    }

    /**
     * The background color of the map. (optional, may include<br>
     * alpha value since 0.15 in the form `#AARRGGBB`)<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getBackgroundcolor() {
        return this.backgroundcolorP;
    }

    /**
     * The background color of the map. (optional, may include<br>
     * alpha value since 0.15 in the form `#AARRGGBB`)<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setBackgroundcolor(String value) {
        this.backgroundcolorP = value;
    }

    /**
     * Stores the next available ID for new layers. This number is<br>
     * stored to prevent reuse of the same ID after layers have been<br>
     * removed.<br>
     * <br>
     * @since 1.2
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getNextlayerid() {
        return this.nextlayeridP;
    }

    /**
     * Stores the next available ID for new layers. This number is<br>
     * stored to prevent reuse of the same ID after layers have been<br>
     * removed.<br>
     * <br>
     * @since 1.2
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setNextlayerid(int value) {
        this.nextlayeridP = value;
    }

    /**
     * Stores the next available ID for new objects. This number<br>
     * is stored to prevent reuse of the same ID after objects<br>
     * have been removed.<br>
     * <br>
     * @since 0.11
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getNextobjectid() {
        return this.nextobjectidP;
    }

    /**
     * Stores the next available ID for new objects. This number<br>
     * is stored to prevent reuse of the same ID after objects<br>
     * have been removed.<br>
     * <br>
     * @since 0.11
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setNextobjectid(int value) {
        this.nextobjectidP = value;
    }

}
