/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.java.bool.BooleanFactory;
import org.allbinary.logic.math.SmallIntegerSingletonFactory;
import org.allbinary.logic.string.StringUtil;



/**
 * While tile layers are very suitable for anything repetitive<br>
 * aligned to the tile grid, sometimes you want to annotate your<br>
 * map with other information, not necessarily aligned to the grid.<br>
 * Hence the objects have their coordinates and size in pixels, but<br>
 * you can still easily align that to the grid when you want to.<br>
 * <br>
 * You generally use objects to add custom information to your tile<br>
 * map, such as spawn points, warps, exits, etc.<br>
 * <br>
 * When the object has a `gid` set, then it is represented by the<br>
 * image of the tile with that global ID. The image alignment<br>
 * currently depends on the map orientation. In orthogonal<br>
 * orientation it's aligned to the bottom-left while in isometric<br>
 * it's aligned to the bottom-center.
 * 
 */
public class MapObjectData {

    /**
     * 
     */
        
    protected Properties propertiesP = new Properties();
    /**
     * @since 1.1
     * 
     */
        
    protected Point pointP = new Point();
    /**
     * @since 0.9
     * 
     */
        
    protected Ellipse ellipseP = new Ellipse();
    /**
     * 
     */
        
    protected Polygon polygonP = new Polygon();
    /**
     * 
     */
        
    protected Polyline polylineP = new Polyline();
    /**
     * @since 1.0
     * 
     */
        
    protected Text textP = new Text();
    /**
     * 
     */
        
    protected ImageData imageP = new ImageData();
    /**
     * Unique ID of the object. Each object that is placed on a map<br>
     * gets a unique id. Even if an object was deleted, no object<br>
     * gets the same ID. Can not be changed in Tiled Qt.<br>
     * <br>
     * @since 0.11
     * 
     */
        
    protected Integer idP = SmallIntegerSingletonFactory.getInstance().getAt(-1);
    /**
     * The name of the object. An arbitrary string.
     * 
     */
        
    protected String nameP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The type of the object. An arbitrary string.
     * 
     */
        
    protected String typeP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The x coordinate of the object in pixels.
     * 
     */
        
    protected double xP;
    /**
     * The y coordinate of the object in pixels.
     * 
     */
        
    protected double yP;
    /**
     * The width of the object in pixels (defaults to 0).
     * 
     */
        
    protected Double widthP = Double.valueOf(0);
    /**
     * The height of the object in pixels (defaults to 0).
     * 
     */
        
    protected Double heightP = Double.valueOf(0);
    /**
     * The rotation of the object in degrees clockwise (defaults to<br>
     *  0).<br>
     * <br>
     * @since 0.10
     * 
     */
        
    protected double rotationP;
    /**
     * An reference to a tile (optional).
     * 
     */
        
    protected Integer gidP = SmallIntegerSingletonFactory.getInstance().getAt(-1);
    /**
     * Whether the object is shown (1) or hidden (0). Defaults to<br>
     *  1.<br>
     * <br>
     * @since 0.9
     * 
     */
        
    protected Boolean visibleP = BooleanFactory.getInstance().FALSE;
    /**
     * A reference to a template file (optional).
     * 
     */
        
    protected String templateP = StringUtil.getInstance().EMPTY_STRING;

    /**
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    
    public Properties getProperties() {
        return this.propertiesP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    
    public void setProperties(Properties value) {
        this.propertiesP = value;
    }

    /**
     * @since 1.1
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    
    public Point getPoint() {
        return this.pointP;
    }

    /**
     * @since 1.1
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    
    public void setPoint(Point value) {
        this.pointP = value;
    }

    /**
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link Ellipse }
     *     
     */
    
    public Ellipse getEllipse() {
        return this.ellipseP;
    }

    /**
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link Ellipse }
     *     
     */
    
    public void setEllipse(Ellipse value) {
        this.ellipseP = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link Polygon }
     *     
     */
    
    public Polygon getPolygon() {
        return this.polygonP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link Polygon }
     *     
     */
    
    public void setPolygon(Polygon value) {
        this.polygonP = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link Polyline }
     *     
     */
    
    public Polyline getPolyline() {
        return this.polylineP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link Polyline }
     *     
     */
    
    public void setPolyline(Polyline value) {
        this.polylineP = value;
    }

    /**
     * @since 1.0
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    
    public Text getText() {
        return this.textP;
    }

    /**
     * @since 1.0
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    
    public void setText(Text value) {
        this.textP = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link ImageData }
     *     
     */
    
    public ImageData getImage() {
        return this.imageP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link ImageData }
     *     
     */
    
    public void setImage(ImageData value) {
        this.imageP = value;
    }

    /**
     * Unique ID of the object. Each object that is placed on a map<br>
     * gets a unique id. Even if an object was deleted, no object<br>
     * gets the same ID. Can not be changed in Tiled Qt.<br>
     * <br>
     * @since 0.11
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getId() {
        return this.idP;
    }

    /**
     * Unique ID of the object. Each object that is placed on a map<br>
     * gets a unique id. Even if an object was deleted, no object<br>
     * gets the same ID. Can not be changed in Tiled Qt.<br>
     * <br>
     * @since 0.11
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setId(Integer value) {
        this.idP = value;
    }

    /**
     * The name of the object. An arbitrary string.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return this.nameP;
    }

    /**
     * The name of the object. An arbitrary string.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.nameP = value;
    }

    /**
     * The type of the object. An arbitrary string.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getType() {
        return this.typeP;
    }

    /**
     * The type of the object. An arbitrary string.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setType(String value) {
        this.typeP = value;
    }

    /**
     * The x coordinate of the object in pixels.
     * 
     */
    
    public double getX() {
        return this.xP;
    }

    /**
     * The x coordinate of the object in pixels.
     * 
     */
    
    public void setX(double value) {
        this.xP = value;
    }

    /**
     * The y coordinate of the object in pixels.
     * 
     */
    
    public double getY() {
        return this.yP;
    }

    /**
     * The y coordinate of the object in pixels.
     * 
     */
    
    public void setY(double value) {
        this.yP = value;
    }

    /**
     * The width of the object in pixels (defaults to 0).
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    
    public Double getWidth() {
        return this.widthP;
    }

    /**
     * The width of the object in pixels (defaults to 0).
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    
    public void setWidth(Double value) {
        this.widthP = value;
    }

    /**
     * The height of the object in pixels (defaults to 0).
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    
    public Double getHeight() {
        return this.heightP;
    }

    /**
     * The height of the object in pixels (defaults to 0).
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    
    public void setHeight(Double value) {
        this.heightP = value;
    }

    /**
     * The rotation of the object in degrees clockwise (defaults to<br>
     *  0).<br>
     * <br>
     * @since 0.10
     * 
     */
    
    public double getRotation() {
        return this.rotationP;
    }

    /**
     * The rotation of the object in degrees clockwise (defaults to<br>
     *  0).<br>
     * <br>
     * @since 0.10
     * 
     */
    
    public void setRotation(double value) {
        this.rotationP = value;
    }

    /**
     * An reference to a tile (optional).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getGid() {
        return this.gidP;
    }

    /**
     * An reference to a tile (optional).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setGid(Integer value) {
        this.gidP = value;
    }

    /**
     * Whether the object is shown (1) or hidden (0). Defaults to<br>
     *  1.<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isVisible() {
        return this.visibleP;
    }

    /**
     * Whether the object is shown (1) or hidden (0). Defaults to<br>
     *  1.<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setVisible(Boolean value) {
        this.visibleP = value;
    }

    /**
     * A reference to a template file (optional).
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getTemplate() {
        return this.templateP;
    }

    /**
     * A reference to a template file (optional).
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setTemplate(String value) {
        this.templateP = value;
    }

}
