/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;



/**
 * While tile layers are very suitable for anything repetitive<br>
 * aligned to the tile grid, sometimes you want to annotate your<br>
 * map with other information, not necessarily aligned to the grid.<br>
 * Hence the objects have their coordinates and size in pixels, but<br>
 * you can still easily align that to the grid when you want to.<br>
 * <br>
 * You generally use objects to add custom information to your tile<br>
 * map, such as spawn points, warps, exits, etc.<br>
 * <br>
 * When the object has a `gid` set, then it is represented by the<br>
 * image of the tile with that global ID. The image alignment<br>
 * currently depends on the map orientation. In orthogonal<br>
 * orientation it's aligned to the bottom-left while in isometric<br>
 * it's aligned to the bottom-center.
 * 
 */
public class MapObjectData {

    /**
     * 
     */
        
    protected Properties properties;
    /**
     * @since 1.1
     * 
     */
        
    protected Point point;
    /**
     * @since 0.9
     * 
     */
        
    protected Ellipse ellipse;
    /**
     * 
     */
        
    protected Polygon polygon;
    /**
     * 
     */
        
    protected Polyline polyline;
    /**
     * @since 1.0
     * 
     */
        
    protected Text text;
    /**
     * 
     */
        
    protected ImageData image;
    /**
     * Unique ID of the object. Each object that is placed on a map<br>
     * gets a unique id. Even if an object was deleted, no object<br>
     * gets the same ID. Can not be changed in Tiled Qt.<br>
     * <br>
     * @since 0.11
     * 
     */
        
    protected Integer id;
    /**
     * The name of the object. An arbitrary string.
     * 
     */
        
    protected String name;
    /**
     * The type of the object. An arbitrary string.
     * 
     */
        
    protected String type;
    /**
     * The x coordinate of the object in pixels.
     * 
     */
        
    protected double x;
    /**
     * The y coordinate of the object in pixels.
     * 
     */
        
    protected double y;
    /**
     * The width of the object in pixels (defaults to 0).
     * 
     */
        
    protected Double width;
    /**
     * The height of the object in pixels (defaults to 0).
     * 
     */
        
    protected Double height;
    /**
     * The rotation of the object in degrees clockwise (defaults to<br>
     *  0).<br>
     * <br>
     * @since 0.10
     * 
     */
        
    protected double rotation;
    /**
     * An reference to a tile (optional).
     * 
     */
        
    protected Integer gid;
    /**
     * Whether the object is shown (1) or hidden (0). Defaults to<br>
     *  1.<br>
     * <br>
     * @since 0.9
     * 
     */
        
    protected Boolean visible;
    /**
     * A reference to a template file (optional).
     * 
     */
        
    protected String template;

    /**
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    
    public Properties getProperties() {
        return properties;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * @since 1.1
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    
    public Point getPoint() {
        return point;
    }

    /**
     * @since 1.1
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    
    public void setPoint(Point value) {
        this.point = value;
    }

    /**
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link Ellipse }
     *     
     */
    
    public Ellipse getEllipse() {
        return ellipse;
    }

    /**
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link Ellipse }
     *     
     */
    
    public void setEllipse(Ellipse value) {
        this.ellipse = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link Polygon }
     *     
     */
    
    public Polygon getPolygon() {
        return polygon;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link Polygon }
     *     
     */
    
    public void setPolygon(Polygon value) {
        this.polygon = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link Polyline }
     *     
     */
    
    public Polyline getPolyline() {
        return polyline;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link Polyline }
     *     
     */
    
    public void setPolyline(Polyline value) {
        this.polyline = value;
    }

    /**
     * @since 1.0
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    
    public Text getText() {
        return text;
    }

    /**
     * @since 1.0
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    
    public void setText(Text value) {
        this.text = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link ImageData }
     *     
     */
    
    public ImageData getImage() {
        return image;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link ImageData }
     *     
     */
    
    public void setImage(ImageData value) {
        this.image = value;
    }

    /**
     * Unique ID of the object. Each object that is placed on a map<br>
     * gets a unique id. Even if an object was deleted, no object<br>
     * gets the same ID. Can not be changed in Tiled Qt.<br>
     * <br>
     * @since 0.11
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getId() {
        return id;
    }

    /**
     * Unique ID of the object. Each object that is placed on a map<br>
     * gets a unique id. Even if an object was deleted, no object<br>
     * gets the same ID. Can not be changed in Tiled Qt.<br>
     * <br>
     * @since 0.11
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * The name of the object. An arbitrary string.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return name;
    }

    /**
     * The name of the object. An arbitrary string.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.name = value;
    }

    /**
     * The type of the object. An arbitrary string.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getType() {
        return type;
    }

    /**
     * The type of the object. An arbitrary string.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setType(String value) {
        this.type = value;
    }

    /**
     * The x coordinate of the object in pixels.
     * 
     */
    
    public double getX() {
        return x;
    }

    /**
     * The x coordinate of the object in pixels.
     * 
     */
    
    public void setX(double value) {
        this.x = value;
    }

    /**
     * The y coordinate of the object in pixels.
     * 
     */
    
    public double getY() {
        return y;
    }

    /**
     * The y coordinate of the object in pixels.
     * 
     */
    
    public void setY(double value) {
        this.y = value;
    }

    /**
     * The width of the object in pixels (defaults to 0).
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    
    public Double getWidth() {
        return width;
    }

    /**
     * The width of the object in pixels (defaults to 0).
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    
    public void setWidth(Double value) {
        this.width = value;
    }

    /**
     * The height of the object in pixels (defaults to 0).
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    
    public Double getHeight() {
        return height;
    }

    /**
     * The height of the object in pixels (defaults to 0).
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * The rotation of the object in degrees clockwise (defaults to<br>
     *  0).<br>
     * <br>
     * @since 0.10
     * 
     */
    
    public double getRotation() {
        return rotation;
    }

    /**
     * The rotation of the object in degrees clockwise (defaults to<br>
     *  0).<br>
     * <br>
     * @since 0.10
     * 
     */
    
    public void setRotation(double value) {
        this.rotation = value;
    }

    /**
     * An reference to a tile (optional).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getGid() {
        return gid;
    }

    /**
     * An reference to a tile (optional).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setGid(Integer value) {
        this.gid = value;
    }

    /**
     * Whether the object is shown (1) or hidden (0). Defaults to<br>
     *  1.<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isVisible() {
        return visible;
    }

    /**
     * Whether the object is shown (1) or hidden (0). Defaults to<br>
     *  1.<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * A reference to a template file (optional).
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getTemplate() {
        return template;
    }

    /**
     * A reference to a template file (optional).
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setTemplate(String value) {
        this.template = value;
    }

}
