/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;



/**
 * 
 */


public class Property {

    /**
     * The name of the property.
     * 
     */
        
    protected String name;
    /**
     * The type of the property. Can be `string` (default), `int`,<br>
     * `float`, `bool`, `color` or `file` (since 0.16, with `color`<br>
     * and `file` added in 0.17).
     * 
     */
        
    protected PropertyType type;
    /**
     * The value of the property.
     * 
     */
        
    protected String value;

    /**
     * The name of the property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return name;
    }

    /**
     * The name of the property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.name = value;
    }

    /**
     * The type of the property. Can be `string` (default), `int`,<br>
     * `float`, `bool`, `color` or `file` (since 0.16, with `color`<br>
     * and `file` added in 0.17).
     * 
     * @return
     *     possible object is
     *     {@link PropertyType }
     *     
     */
    
    public PropertyType getType() {
        return type;
    }

    /**
     * The type of the property. Can be `string` (default), `int`,<br>
     * `float`, `bool`, `color` or `file` (since 0.16, with `color`<br>
     * and `file` added in 0.17).
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyType }
     *     
     */
    
    public void setType(PropertyType value) {
        this.type = value;
    }

    /**
     * The value of the property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getValue() {
        return value;
    }

    /**
     * The value of the property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setValue(String value) {
        this.value = value;
    }

}
