/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.util.BasicArrayList;
import org.allbinary.util.BasicArrayListD;



/**
 * 
 */
//enum
public class RenderOrder {


    /**
     * 
     */
    public static final RenderOrder RIGHT_DOWN = new RenderOrder("right-down");

    /**
     * 
     */
    public static final RenderOrder RIGHT_UP = new RenderOrder("right-up");

    /**
     * 
     */
    public static final RenderOrder LEFT_DOWN = new RenderOrder("left-down");

    /**
     * 
     */
    public static final RenderOrder LEFT_UP = new RenderOrder("left-up");
        
    private static final BasicArrayList RENDER_ORDER_LIST = new BasicArrayListD();

    private final String value;

    RenderOrder(String v) {
        this.value = v;
        RenderOrder.RENDER_ORDER_LIST.add(this);
    }

    public String value() {
        return this.value;
    }

    public static RenderOrder fromValue(String v) {
        final int size = RenderOrder.RENDER_ORDER_LIST.size();
        RenderOrder c;
        for (int index = 0; index < size; index++) {
            c = (RenderOrder) RenderOrder.RENDER_ORDER_LIST.get(index);
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
