/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.java.bool.BooleanFactory;
import org.allbinary.logic.math.SmallIntegerSingletonFactory;
import org.allbinary.logic.string.StringUtil;



/**
 * Used to mark an object as a text object. Contains the actual<br>
 * text as character data.
 * 
 */
public class Text {

    /**
     * 
     */
        
    protected String valueP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The font family used (default: "sand-serif")
     * 
     */
        
    protected String fontfamilyP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The size of the font in pixels (not using points,<br>
     * because other sizes in the TMX format are also using<br>
     * pixels) (default: 16)
     * 
     */
        
    protected Integer pixelsizeP = SmallIntegerSingletonFactory.getInstance().getAt(-1);
    /**
     * Whether word wrapping is enabled (1) or disabled<br>
     * (0). Defaults to 0.
     * 
     */
        
    protected Boolean wrapP = BooleanFactory.getInstance().FALSE;
    /**
     * Color of the text in `#AARRGGBB` or `#RRGGBB` format<br>
     * (default: #000000)
     * 
     */
        
    protected String colorP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * Whether the font is bold (1) or not (0). Defaults to<br>
     *  0.
     * 
     */
        
    protected Boolean boldP = BooleanFactory.getInstance().FALSE;
    /**
     * Whether the font is italic (1) or not (0). Defaults<br>
     * to 0.
     * 
     */
        
    protected Boolean italicP = BooleanFactory.getInstance().FALSE;
    /**
     * Whether a line should be drawn below the text (1) or<br>
     * not (0). Defaults to 0.
     * 
     */
        
    protected Boolean underlineP = BooleanFactory.getInstance().FALSE;
    /**
     * Whether a line should be drawn through the text (1)<br>
     * or not (0). Defaults to 0.
     * 
     */
        
    protected Boolean strikeoutP = BooleanFactory.getInstance().FALSE;
    /**
     * Whether kerning should be used while rendering the<br>
     * text (1) or not (0). Default to 1.
     * 
     */
        
    protected Boolean kerningP = BooleanFactory.getInstance().FALSE;
    /**
     * Horizontal alignment of the text within the object<br>
     * (`left` (default), `center` or `right`)
     * 
     */
        
    protected HorizontalAlignment halignP = HorizontalAlignment.CENTER;
    /**
     * Vertical alignment of the text within the object<br>
     * (`left` (default), `center` or `right`)
     * 
     */
        
    protected VerticalAlignment valignP = VerticalAlignment.CENTER;

    /**
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getValue() {
        return this.valueP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setValue(String value) {
        this.valueP = value;
    }

    /**
     * The font family used (default: "sand-serif")
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getFontfamily() {
        return this.fontfamilyP;
    }

    /**
     * The font family used (default: "sand-serif")
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setFontfamily(String value) {
        this.fontfamilyP = value;
    }

    /**
     * The size of the font in pixels (not using points,<br>
     * because other sizes in the TMX format are also using<br>
     * pixels) (default: 16)
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getPixelsize() {
        return this.pixelsizeP;
    }

    /**
     * The size of the font in pixels (not using points,<br>
     * because other sizes in the TMX format are also using<br>
     * pixels) (default: 16)
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setPixelsize(Integer value) {
        this.pixelsizeP = value;
    }

    /**
     * Whether word wrapping is enabled (1) or disabled<br>
     * (0). Defaults to 0.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isWrap() {
        return this.wrapP;
    }

    /**
     * Whether word wrapping is enabled (1) or disabled<br>
     * (0). Defaults to 0.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setWrap(Boolean value) {
        this.wrapP = value;
    }

    /**
     * Color of the text in `#AARRGGBB` or `#RRGGBB` format<br>
     * (default: #000000)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getColor() {
        return this.colorP;
    }

    /**
     * Color of the text in `#AARRGGBB` or `#RRGGBB` format<br>
     * (default: #000000)
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setColor(String value) {
        this.colorP = value;
    }

    /**
     * Whether the font is bold (1) or not (0). Defaults to<br>
     *  0.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isBold() {
        return this.boldP;
    }

    /**
     * Whether the font is bold (1) or not (0). Defaults to<br>
     *  0.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setBold(Boolean value) {
        this.boldP = value;
    }

    /**
     * Whether the font is italic (1) or not (0). Defaults<br>
     * to 0.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isItalic() {
        return this.italicP;
    }

    /**
     * Whether the font is italic (1) or not (0). Defaults<br>
     * to 0.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setItalic(Boolean value) {
        this.italicP = value;
    }

    /**
     * Whether a line should be drawn below the text (1) or<br>
     * not (0). Defaults to 0.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isUnderline() {
        return this.underlineP;
    }

    /**
     * Whether a line should be drawn below the text (1) or<br>
     * not (0). Defaults to 0.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setUnderline(Boolean value) {
        this.underlineP = value;
    }

    /**
     * Whether a line should be drawn through the text (1)<br>
     * or not (0). Defaults to 0.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isStrikeout() {
        return this.strikeoutP;
    }

    /**
     * Whether a line should be drawn through the text (1)<br>
     * or not (0). Defaults to 0.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setStrikeout(Boolean value) {
        this.strikeoutP = value;
    }

    /**
     * Whether kerning should be used while rendering the<br>
     * text (1) or not (0). Default to 1.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    
    public Boolean isKerning() {
        return this.kerningP;
    }

    /**
     * Whether kerning should be used while rendering the<br>
     * text (1) or not (0). Default to 1.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    
    public void setKerning(Boolean value) {
        this.kerningP = value;
    }

    /**
     * Horizontal alignment of the text within the object<br>
     * (`left` (default), `center` or `right`)
     * 
     * @return
     *     possible object is
     *     {@link HorizontalAlignment }
     *     
     */
    
    public HorizontalAlignment getHalign() {
        return this.halignP;
    }

    /**
     * Horizontal alignment of the text within the object<br>
     * (`left` (default), `center` or `right`)
     * 
     * @param value
     *     allowed object is
     *     {@link HorizontalAlignment }
     *     
     */
    
    public void setHalign(HorizontalAlignment value) {
        this.halignP = value;
    }

    /**
     * Vertical alignment of the text within the object<br>
     * (`left` (default), `center` or `right`)
     * 
     * @return
     *     possible object is
     *     {@link VerticalAlignment }
     *     
     */
    
    public VerticalAlignment getValign() {
        return this.valignP;
    }

    /**
     * Vertical alignment of the text within the object<br>
     * (`left` (default), `center` or `right`)
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalAlignment }
     *     
     */
    
    public void setValign(VerticalAlignment value) {
        this.valignP = value;
    }

}
