/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.util.BasicArrayList;

/**
 * If there are multiple `tileset` elements, they are in ascending<br>
 * order of their `firstgid` attribute. The first tileset always<br>
 * has a `firstgid` value of 1\. Since Tiled 0.15, image collection<br>
 * tilesets do not necessarily number their tiles consecutively<br>
 * since gaps can occur when removing tiles.
 * 
 */
public class TileSetData {

    /**
     * @since 0.8
     * 
     */
        
    protected TileOffset tileoffset;
    /**
     * @since 1.0
     * 
     */
        
    protected Grid grid;
    /**
     * @since 0.8
     * 
     */
        
    protected Properties properties;
    /**
     * 
     */
        
    protected ImageData imageData;
    /**
     * @since 0.9
     * 
     */
    
    protected TerrainTypes terraintypes;
    /**
     * 
     */
        
    protected BasicArrayList internalTiles;
    /**
     * @since 1.1
     * 
     */
        
    protected WangSets wangsets;
    /**
     * The first global tile ID of this tileset (this global ID<br>
     * maps to the first tile in this tileset).
     * 
     */
        
    protected Integer firstgid;
    /**
     * The name of this tileset.
     * 
     */
        
    protected String name;
    /**
     * If this tileset is stored in an external TSX (Tile Set XML)<br>
     * file, this attribute refers to that file. That TSX file has<br>
     * the same structure as the element described here. (There is<br>
     * the **firstgid** attribute missing and this source attribute<br>
     * is also not there. These two attributes are kept in the TMX<br>
     * map, since they are map specific.)
     * 
     */
            
    protected String source;
    /**
     * The (maximum) width of the tiles in this tileset.
     * 
     */
        
    protected int tileWidth;
    /**
     * The (maximum) height of the tiles in this tileset.
     * 
     */
        
    protected int tileHeight;
    /**
     * The spacing in pixels between the tiles in this tileset<br>
     * (applies to the tileset image).
     * 
     */
        
    protected Integer tileSpacing;
    /**
     * The margin around the tiles in this tileset (applies to the<br>
     * tileset image).
     * 
     */
        
    protected Integer tileMargin;
    /**
     * The number of tiles in this tileset<br>
     * <br>
     * @since 0.13
     * 
     */
        
    protected Integer tilecount;
    /**
     * The number of tile columns in the tileset. For image<br>
     * collection tilesets it is editable and is used when<br>
     * displaying the tileset.<br>
     * <br>
     * @since 0.15
     * 
     */
        
    protected int columns;

    /**
     * @since 0.8
     * 
     * @return
     *     possible object is
     *     {@link TileOffset }
     *     
     */
    
    public TileOffset getTileoffset() {
        return tileoffset;
    }

    /**
     * @since 0.8
     * 
     * @param value
     *     allowed object is
     *     {@link TileOffset }
     *     
     */
    
    public void setTileoffset(TileOffset value) {
        this.tileoffset = value;
    }

    /**
     * @since 1.0
     * 
     * @return
     *     possible object is
     *     {@link Grid }
     *     
     */
    
    public Grid getGrid() {
        return grid;
    }

    /**
     * @since 1.0
     * 
     * @param value
     *     allowed object is
     *     {@link Grid }
     *     
     */
    
    public void setGrid(Grid value) {
        this.grid = value;
    }

    /**
     * @since 0.8
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    
    public Properties getProperties() {
        return properties;
    }

    /**
     * @since 0.8
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link ImageData }
     *     
     */
    
    public ImageData getImageData() {
        return imageData;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link ImageData }
     *     
     */
    
    public void setImageData(ImageData value) {
        this.imageData = value;
    }

    /**
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link TerrainTypes }
     *     
     */
    
    public TerrainTypes getTerraintypes() {
        return terraintypes;
    }

    /**
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link TerrainTypes }
     *     
     */
    
    public void setTerraintypes(TerrainTypes value) {
        this.terraintypes = value;
    }

    /**
     * 
     */
    
    public BasicArrayList getInternalTiles() {
        if (internalTiles == null) {
            internalTiles = new BasicArrayList();
        }
        return this.internalTiles;
    }

    /**
     * @since 1.1
     * 
     * @return
     *     possible object is
     *     {@link WangSets }
     *     
     */
    
    public WangSets getWangsets() {
        return wangsets;
    }

    /**
     * @since 1.1
     * 
     * @param value
     *     allowed object is
     *     {@link WangSets }
     *     
     */
    
    public void setWangsets(WangSets value) {
        this.wangsets = value;
    }

    /**
     * The first global tile ID of this tileset (this global ID<br>
     * maps to the first tile in this tileset).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getFirstgid() {
        return firstgid;
    }

    /**
     * The first global tile ID of this tileset (this global ID<br>
     * maps to the first tile in this tileset).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setFirstgid(Integer value) {
        this.firstgid = value;
    }

    /**
     * The name of this tileset.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return name;
    }

    /**
     * The name of this tileset.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.name = value;
    }

    /**
     * If this tileset is stored in an external TSX (Tile Set XML)<br>
     * file, this attribute refers to that file. That TSX file has<br>
     * the same structure as the element described here. (There is<br>
     * the **firstgid** attribute missing and this source attribute<br>
     * is also not there. These two attributes are kept in the TMX<br>
     * map, since they are map specific.)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getSource() {
        return source;
    }

    /**
     * If this tileset is stored in an external TSX (Tile Set XML)<br>
     * file, this attribute refers to that file. That TSX file has<br>
     * the same structure as the element described here. (There is<br>
     * the **firstgid** attribute missing and this source attribute<br>
     * is also not there. These two attributes are kept in the TMX<br>
     * map, since they are map specific.)
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * The (maximum) width of the tiles in this tileset.
     * 
     */
    
    public int getTileWidth() {
        return tileWidth;
    }

    /**
     * The (maximum) width of the tiles in this tileset.
     * 
     */
    
    public void setTileWidth(int value) {
        this.tileWidth = value;
    }

    /**
     * The (maximum) height of the tiles in this tileset.
     * 
     */
    
    public int getTileHeight() {
        return tileHeight;
    }

    /**
     * The (maximum) height of the tiles in this tileset.
     * 
     */
    
    public void setTileHeight(int value) {
        this.tileHeight = value;
    }

    /**
     * The spacing in pixels between the tiles in this tileset<br>
     * (applies to the tileset image).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getTileSpacing() {
        return tileSpacing;
    }

    /**
     * The spacing in pixels between the tiles in this tileset<br>
     * (applies to the tileset image).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTileSpacing(Integer value) {
        this.tileSpacing = value;
    }

    /**
     * The margin around the tiles in this tileset (applies to the<br>
     * tileset image).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getTileMargin() {
        return tileMargin;
    }

    /**
     * The margin around the tiles in this tileset (applies to the<br>
     * tileset image).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTileMargin(Integer value) {
        this.tileMargin = value;
    }

    /**
     * The number of tiles in this tileset<br>
     * <br>
     * @since 0.13
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getTilecount() {
        return tilecount;
    }

    /**
     * The number of tiles in this tileset<br>
     * <br>
     * @since 0.13
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTilecount(Integer value) {
        this.tilecount = value;
    }

    /**
     * The number of tile columns in the tileset. For image<br>
     * collection tilesets it is editable and is used when<br>
     * displaying the tileset.<br>
     * <br>
     * @since 0.15
     * 
     */
    
    public int getColumns() {
        return columns;
    }

    /**
     * The number of tile columns in the tileset. For image<br>
     * collection tilesets it is editable and is used when<br>
     * displaying the tileset.<br>
     * <br>
     * @since 0.15
     * 
     */
    
    public void setColumns(int value) {
        this.columns = value;
    }

}
