/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.util.BasicArrayList;
import org.allbinary.util.BasicArrayListD;

/**
 * 
 * 
 */
public class TileData {

    /**
     * 
     */
        
    protected Properties properties;
    /**
     * @since 0.9
     * 
     */
        
    protected ImageData imageData;
    /**
     * @since 0.10
     * 
     */
        
    protected BasicArrayList objectgroup;
    /**
     * @since 0.10
     * 
     */
    
    protected Animation animation = Animation.NULL_ANIMATION;
    /**
     * The local tile ID within its tileset.
     * 
     */
        
    protected Integer id;
    /**
     * The type of the tile. Refers to an object type and is used<br>
     * by tile objects. (optional)<br>
     * <br>
     * @since 1.0
     * 
     */
        
    protected String type;
    /**
     * Defines the terrain type of each corner of the tile, given<br>
     * as comma-separated indexes in the terrain types array in the<br>
     * order top-left, top-right, bottom-left, bottom-right.<br>
     * Leaving out a value means that corner has no terrain.<br>
     * (optional)<br>
     * <br>
     * @since 0.9
     * 
     */
        
    protected String terrain;
    /**
     * A percentage indicating the probability that this tile is<br>
     * chosen when it competes with others while editing with the<br>
     * terrain tool. (optional)<br>
     * <br>
     * @since 0.9
     * 
     */
        
    protected Double probability;

    /**
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    
    public Properties getProperties() {
        return this.properties;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link ImageData }
     *     
     */
    
    public ImageData getImageData() {
        return this.imageData;
    }

    /**
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link ImageData }
     *     
     */
    
    public void setImageData(ImageData value) {
        this.imageData = value;
    }

    /**
     * @since 0.10
     * 
     */
    
    public BasicArrayList getObjectgroup() {
        if (this.objectgroup == null) {
            this.objectgroup = new BasicArrayListD();
        }
        return this.objectgroup;
    }

    /**
     * @since 0.10
     * 
     * @return
     *     possible object is
     *     {@link Animation }
     *     
     */
    
    public Animation getAnimation() {
        return this.animation;
    }

    /**
     * @since 0.10
     * 
     * @param value
     *     allowed object is
     *     {@link Animation }
     *     
     */
    
    public void setAnimation(Animation value) {
        this.animation = value;
    }

    /**
     * The local tile ID within its tileset.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getId() {
        return this.id;
    }

    /**
     * The local tile ID within its tileset.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * The type of the tile. Refers to an object type and is used<br>
     * by tile objects. (optional)<br>
     * <br>
     * @since 1.0
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getType() {
        return this.type;
    }

    /**
     * The type of the tile. Refers to an object type and is used<br>
     * by tile objects. (optional)<br>
     * <br>
     * @since 1.0
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Defines the terrain type of each corner of the tile, given<br>
     * as comma-separated indexes in the terrain types array in the<br>
     * order top-left, top-right, bottom-left, bottom-right.<br>
     * Leaving out a value means that corner has no terrain.<br>
     * (optional)<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getTerrain() {
        return this.terrain;
    }

    /**
     * Defines the terrain type of each corner of the tile, given<br>
     * as comma-separated indexes in the terrain types array in the<br>
     * order top-left, top-right, bottom-left, bottom-right.<br>
     * Leaving out a value means that corner has no terrain.<br>
     * (optional)<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setTerrain(String value) {
        this.terrain = value;
    }

    /**
     * A percentage indicating the probability that this tile is<br>
     * chosen when it competes with others while editing with the<br>
     * terrain tool. (optional)<br>
     * <br>
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    
    public Double getProbability() {
        return this.probability;
    }

    /**
     * A percentage indicating the probability that this tile is<br>
     * chosen when it competes with others while editing with the<br>
     * terrain tool. (optional)<br>
     * <br>
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    
    public void setProbability(Double value) {
        this.probability = value;
    }

}
