/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.string.StringUtil;
import org.allbinary.util.BasicArrayList;
import org.allbinary.util.BasicArrayListD;

/**
 * If there are multiple `tileset` elements, they are in ascending<br>
 * order of their `firstgid` attribute. The first tileset always<br>
 * has a `firstgid` value of 1\. Since Tiled 0.15, image collection<br>
 * tilesets do not necessarily number their tiles consecutively<br>
 * since gaps can occur when removing tiles.
 * 
 */
public class TileSetData {

    /**
     * @since 0.8
     * 
     */
        
    protected TileOffset tileoffsetP = new TileOffset();
    /**
     * @since 1.0
     * 
     */
        
    protected Grid gridP = new Grid();
    /**
     * @since 0.8
     * 
     */
        
    protected Properties propertiesP = new Properties();
    /**
     * 
     */
        
    protected ImageData imageDataP = new ImageData();
    /**
     * @since 0.9
     * 
     */
    
    protected TerrainTypes terraintypesP = new TerrainTypes();
    /**
     * 
     */
        
    protected final BasicArrayList internalTilesP = new BasicArrayListD();
    /**
     * @since 1.1
     * 
     */
        
    protected WangSets wangsetsP = new WangSets();
    /**
     * The first global tile ID of this tileset (this global ID<br>
     * maps to the first tile in this tileset).
     * 
     */
        
    protected int firstgidP;
    /**
     * The name of this tileset.
     * 
     */
        
    protected String nameP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * If this tileset is stored in an external TSX (Tile Set XML)<br>
     * file, this attribute refers to that file. That TSX file has<br>
     * the same structure as the element described here. (There is<br>
     * the **firstgid** attribute missing and this source attribute<br>
     * is also not there. These two attributes are kept in the TMX<br>
     * map, since they are map specific.)
     * 
     */
            
    protected String sourceP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The (maximum) width of the tiles in this tileset.
     * 
     */
        
    protected int tileWidthP;
    /**
     * The (maximum) height of the tiles in this tileset.
     * 
     */
        
    protected int tileHeightP;
    /**
     * The spacing in pixels between the tiles in this tileset<br>
     * (applies to the tileset image).
     * 
     */
        
    protected int tileSpacingP;
    /**
     * The margin around the tiles in this tileset (applies to the<br>
     * tileset image).
     * 
     */
        
    protected int tileMarginP;
    /**
     * The number of tiles in this tileset<br>
     * <br>
     * @since 0.13
     * 
     */
        
    protected int tilecountP;
    /**
     * The number of tile columns in the tileset. For image<br>
     * collection tilesets it is editable and is used when<br>
     * displaying the tileset.<br>
     * <br>
     * @since 0.15
     * 
     */
        
    protected int columnsP;

    /**
     * @since 0.8
     * 
     * @return
     *     possible object is
     *     {@link TileOffset }
     *     
     */
    
    public TileOffset getTileoffset() {
        return this.tileoffsetP;
    }

    /**
     * @since 0.8
     * 
     * @param value
     *     allowed object is
     *     {@link TileOffset }
     *     
     */
    
    public void setTileoffset(TileOffset value) {
        this.tileoffsetP = value;
    }

    /**
     * @since 1.0
     * 
     * @return
     *     possible object is
     *     {@link Grid }
     *     
     */
    
    public Grid getGrid() {
        return this.gridP;
    }

    /**
     * @since 1.0
     * 
     * @param value
     *     allowed object is
     *     {@link Grid }
     *     
     */
    
    public void setGrid(Grid value) {
        this.gridP = value;
    }

    /**
     * @since 0.8
     * 
     * @return
     *     possible object is
     *     {@link PropertiesData }
     *     
     */
    
    public Properties getProperties() {
        return this.propertiesP;
    }

    /**
     * @since 0.8
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesData }
     *     
     */
    
    public void setProperties(Properties value) {
        this.propertiesP = value;
    }

    /**
     * 
     * @return
     *     possible object is
     *     {@link ImageData }
     *     
     */
    
    public ImageData getImageData() {
        return this.imageDataP;
    }

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link ImageData }
     *     
     */
    
    public void setImageData(ImageData value) {
        this.imageDataP = value;
    }

    /**
     * @since 0.9
     * 
     * @return
     *     possible object is
     *     {@link TerrainTypes }
     *     
     */
    
    public TerrainTypes getTerraintypes() {
        return this.terraintypesP;
    }

    /**
     * @since 0.9
     * 
     * @param value
     *     allowed object is
     *     {@link TerrainTypes }
     *     
     */
    
    public void setTerraintypes(TerrainTypes value) {
        this.terraintypesP = value;
    }

    /**
     * 
     */
    
    public BasicArrayList getInternalTiles() {
        return this.internalTilesP;
    }

    /**
     * @since 1.1
     * 
     * @return
     *     possible object is
     *     {@link WangSets }
     *     
     */
    
    public WangSets getWangsets() {
        return this.wangsetsP;
    }

    /**
     * @since 1.1
     * 
     * @param value
     *     allowed object is
     *     {@link WangSets }
     *     
     */
    
    public void setWangsets(WangSets value) {
        this.wangsetsP = value;
    }

    /**
     * The first global tile ID of this tileset (this global ID<br>
     * maps to the first tile in this tileset).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getFirstgid() {
        return this.firstgidP;
    }

    /**
     * The first global tile ID of this tileset (this global ID<br>
     * maps to the first tile in this tileset).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setFirstgid(int value) {
        this.firstgidP = value;
    }

    /**
     * The name of this tileset.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return this.nameP;
    }

    /**
     * The name of this tileset.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.nameP = value;
    }

    /**
     * If this tileset is stored in an external TSX (Tile Set XML)<br>
     * file, this attribute refers to that file. That TSX file has<br>
     * the same structure as the element described here. (There is<br>
     * the **firstgid** attribute missing and this source attribute<br>
     * is also not there. These two attributes are kept in the TMX<br>
     * map, since they are map specific.)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getSource() {
        return this.sourceP;
    }

    /**
     * If this tileset is stored in an external TSX (Tile Set XML)<br>
     * file, this attribute refers to that file. That TSX file has<br>
     * the same structure as the element described here. (There is<br>
     * the **firstgid** attribute missing and this source attribute<br>
     * is also not there. These two attributes are kept in the TMX<br>
     * map, since they are map specific.)
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setSource(String value) {
        this.sourceP = value;
    }

    /**
     * The (maximum) width of the tiles in this tileset.
     * 
     */
    
    public int getTileWidth() {
        return this.tileWidthP;
    }

    /**
     * The (maximum) width of the tiles in this tileset.
     * 
     */
    
    public void setTileWidth(int value) {
        this.tileWidthP = value;
    }

    /**
     * The (maximum) height of the tiles in this tileset.
     * 
     */
    
    public int getTileHeight() {
        return this.tileHeightP;
    }

    /**
     * The (maximum) height of the tiles in this tileset.
     * 
     */
    
    public void setTileHeight(int value) {
        this.tileHeightP = value;
    }

    /**
     * The spacing in pixels between the tiles in this tileset<br>
     * (applies to the tileset image).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getTileSpacing() {
        return this.tileSpacingP;
    }

    /**
     * The spacing in pixels between the tiles in this tileset<br>
     * (applies to the tileset image).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTileSpacing(int value) {
        this.tileSpacingP = value;
    }

    /**
     * The margin around the tiles in this tileset (applies to the<br>
     * tileset image).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getTileMargin() {
        return this.tileMarginP;
    }

    /**
     * The margin around the tiles in this tileset (applies to the<br>
     * tileset image).
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTileMargin(int value) {
        this.tileMarginP = value;
    }

    /**
     * The number of tiles in this tileset<br>
     * <br>
     * @since 0.13
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getTilecount() {
        return this.tilecountP;
    }

    /**
     * The number of tiles in this tileset<br>
     * <br>
     * @since 0.13
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTilecount(int value) {
        this.tilecountP = value;
    }

    /**
     * The number of tile columns in the tileset. For image<br>
     * collection tilesets it is editable and is used when<br>
     * displaying the tileset.<br>
     * <br>
     * @since 0.15
     * 
     */
    
    public int getColumns() {
        return this.columnsP;
    }

    /**
     * The number of tile columns in the tileset. For image<br>
     * collection tilesets it is editable and is used when<br>
     * displaying the tileset.<br>
     * <br>
     * @since 0.15
     * 
     */
    
    public void setColumns(int value) {
        this.columnsP = value;
    }

}
