/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 Thorbjørn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;



/**
 * Defines a Wang tile, by referring to a tile in the tileset and<br>
 * associating it with a certain Wang ID.
 * 
 */


public class WangTile {

    /**
     * The tile ID.
     * 
     */
        
    protected Integer tileid;
    /**
     * The Wang ID, which is a 32-bit unsigned integer stored in<br>
     * the format 0xCECECECE (where each C is a corner color and<br>
     * each E is an edge color, from right to left clockwise,<br>
     * starting with the top edge)
     * 
     */
        
    protected String wangid;

    /**
     * The tile ID.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public Integer getTileid() {
        return tileid;
    }

    /**
     * The tile ID.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTileid(Integer value) {
        this.tileid = value;
    }

    /**
     * The Wang ID, which is a 32-bit unsigned integer stored in<br>
     * the format 0xCECECECE (where each C is a corner color and<br>
     * each E is an edge color, from right to left clockwise,<br>
     * starting with the top edge)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getWangid() {
        return wangid;
    }

    /**
     * The Wang ID, which is a 32-bit unsigned integer stored in<br>
     * the format 0xCECECECE (where each C is a corner color and<br>
     * each E is an edge color, from right to left clockwise,<br>
     * starting with the top edge)
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setWangid(String value) {
        this.wangid = value;
    }

}
