/*-
 * #%L
 * TiledJSONJavaLibrary
 * %%
 * Copyright (C) 2004 - 2023 ThorbjUNICODEcharrrn Lindeijer <thorbjorn@lindeijer.nl>
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.16 at 03:17:09 AM CDT 
//


package org.mapeditor.core;

import org.allbinary.logic.string.StringUtil;
import org.allbinary.util.BasicArrayList;
import org.allbinary.util.BasicArrayListD;

/**
 * Defines a list of corner colors and a list of edge colors, and<br>
 * any number of Wang tiles using these colors.
 * 
 */
public class WangSet {

    /**
     * 
     */
        
    protected final BasicArrayList wangcornercolorP = new BasicArrayListD();
    /**
     * 
     */
        
    protected final BasicArrayList wangedgecolorP = new BasicArrayListD();
    /**
     * 
     */
        
    protected final BasicArrayList wangtileP = new BasicArrayListD();
    /**
     * The name of the Wang set.
     * 
     */
        
    protected String nameP = StringUtil.getInstance().EMPTY_STRING;
    /**
     * The tile ID of the tile representing this Wang set.
     * 
     */
        
    protected int tileP;

    /**
     * 
     */
    
    public BasicArrayList getWangcornercolor() {
        return this.wangcornercolorP;
    }

    /**
     * 
     */
    
    public BasicArrayList getWangedgecolor() {
        return this.wangedgecolorP;
    }

    /**
     * 
     */
    
    public BasicArrayList getWangtile() {
        return this.wangtileP;
    }

    /**
     * The name of the Wang set.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getName() {
        return this.nameP;
    }

    /**
     * The name of the Wang set.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setName(String value) {
        this.nameP = value;
    }

    /**
     * The tile ID of the tile representing this Wang set.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    
    public int getTile() {
        return this.tileP;
    }

    /**
     * The tile ID of the tile representing this Wang set.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    
    public void setTile(int value) {
        this.tileP = value;
    }

}
